services:

  postgres:
    image: postgres
    container_name: postgr
    environment:
      POSTGRES_PASSWORD: pass 
      POSTGRES_USER: username
      POSTGRES_DB: database
    networks:
      - mynetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data # after re-runnig DB-container we wont lose DB's data , and they will save in hard disk , bc inside of docker is connected to outside of docker 
        # informations inside the docker , will be saved outside of docker as well , so they wont be deleted 
        

  aiwebapp:
    image: aiwebapp
    container_name: quart_webapp
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - mynetwork
    ports:
      - "8080:5000"
    volumes:
      - ".:/app"
    environment:
      - DATABASE_URL=postgresql://username:pass@postgr:5432/database
    depends_on:
      - postgres  
      - face_analysis
      - object_detection


  face_analysis:
    image: fastapi
    container_name: FaceAnalysis
    build:
      context: ../FastAPI_FaceAnalysis
      dockerfile: Dockerfile
    networks:
      - mynetwork
    volumes:
      - ".:/app"
    # ports:
    #   - "8000:8000"

  object_detection:
    image: objflask
    container_name: objectDetection
    build:
      context: ../Flask_ObjectDetection
      dockerfile: Dockerfile
    networks:
      - mynetwork
    volumes:
      - ".:/app"
    # ports:
    #   - "5001:5000"

networks: 
  mynetwork :


volumes:
  postgres_data:




# docker run  --network mynetwork --name postgr -e POSTGRES_PASSWORD=pass -e POSTGRES_USER=username -e POSTGRES_DB=database -d postgres
# docker run -v .:/app -p 8080:5000 --network mynetwork webapp
# .:/app 
# . means current folder outside docker مسیر بیرون داکر و فایل های فعلی 
# /app means , current folder inside docker درون داکر فایل این مسیر رو تعریف کردیم به عنوان فولدری به نام اپ 