services:

  postgres:
    image: postgres
    container_name: postgr
    environment:
      POSTGRES_PASSWORD: pass 
      POSTGRES_USER: username
      POSTGRES_DB: database
    networks:
      - aiapp_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data # after re-runnig DB-container we wont lose DB's data , and they will save in hard disk , bc inside of docker is connected to outside of docker 
        # informations inside the docker , will be saved outside of docker as well , so they wont be deleted 
        

  aiwebapp:
    image: aiwebapp
    container_name: quart_webapp
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - aiapp_postgres
      - aiapp_faceanalysis
      - aiapp_objdetection
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
    depends_on:
      - postgres  
      - face_analysis
      - object_detection


  face_analysis:
    image: fastapi
    container_name: FaceAnalysis
    build:
      context: ../FastAPI_FaceAnalysis
      dockerfile: ../FastAPI_FaceAnalysis/Dockerfile
    networks:
      - aiapp_faceanalysis
    volumes:
      - "../FastAPI_FaceAnalysis:./app"
    ports:
      - "8000:8000"


  object_detection:
    image: objflask
    container_name: objectDetection
    build:
      context: ../Flask_ObjectDetection
      dockerfile: ../Flask_ObjectDetection/Dockerfile
    networks:
      - aiapp_objdetection
    volumes:
      - "../Flask_ObjectDetection:/appf"
    ports:
      - "5000:5000"


networks: 
  aiapp_faceanalysis :
  aiapp_objdetection :
  aiapp_postgres :


volumes:
  postgres_data:

